# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CoCo - Find serviced apartments Chiang Mai perfect for digital nomads.


# This is the place to set up the contact form recipient
# email: your-email@example.com

description: > # this means to ignore newlines until "baseurl:"
  CoCo is curated specifically for digital nomads. Find and rent an apartment with us and we'll plug you into the services and amenities you need to hit the ground running. Members get access to our friendly concierge service as well as our awesome community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  load_paths:
    - bower_components/

incremental: true

exclude: ['gulpfile.js', 'Gemfile', 'Gemfile.lock']

collections:
  rooms:
    output: true
    permalink: /rooms/:name/
  pages:
    output: true
    permalink: /:name/


defaults:
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

paginate: 4
paginate_path: "/blog/page/:num"

# This is the place to set up the commenting system
# disqus:
#   shortname: your-disqus-shortname

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
